import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useState, type FormEvent } from 'react';
import { Eye, EyeOff, KeyRound, LockKeyhole, Save } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { OfflineNotice, PageHeading } from '@/components/vpn-shell';
import { useVpn } from '@/components/vpn-provider';
import type { Credentials } from '@/lib/vpn';

export const Route = createFileRoute('/credentials')({ head: () => ({ meta: [{ title: 'Credentials | VPN AP Manager' }, { name: 'description', content: 'Manage NordVPN, WireGuard, and OpenVPN credentials for your access points.' }, { property: 'og:title', content: 'VPN AP Manager Credentials' }, { property: 'og:description', content: 'Manage NordVPN, WireGuard, and OpenVPN credentials for your access points.' }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] }), component: CredentialsPage });
function CredentialsPage() {
  const { health, request, notify } = useVpn();
  const [status, setStatus] = useState<Credentials | null>(null);
  const [values, setValues] = useState({ nordvpn_token: '', wireguard_private_key: '', openvpn_user: '', openvpn_password: '' });
  const [visible, setVisible] = useState<Record<string, boolean>>({});
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (health) void request<Credentials>('/credentials').then(setStatus).catch(caught => setError(caught instanceof Error ? caught.message : 'Could not load credential status.')); }, [health?.status, request]);
  const save = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError('');
    const payload = Object.fromEntries(Object.entries(values).filter(([, value]) => value.trim()));
    if (!Object.keys(payload).length) { setError('Enter a new value before saving.'); setBusy(false); return; }
    try { await request('/credentials', { method: 'PATCH', body: JSON.stringify(payload) }); setStatus(await request<Credentials>('/credentials')); setValues({ nordvpn_token: '', wireguard_private_key: '', openvpn_user: '', openvpn_password: '' }); notify('Credentials updated.'); }
    catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not save credentials.'); } finally { setBusy(false); }
  };
  const field = (key: keyof typeof values, label: string, hint: string, configured?: boolean) => <div><div className="flex flex-wrap items-center justify-between gap-2"><label className="label" htmlFor={key}>{label}</label>{configured && <span className="font-mono text-[11px] text-success">Configured</span>}</div><div className="relative mt-2"><input id={key} className="field pr-12" autoComplete="off" type={visible[key] ? 'text' : key === 'openvpn_user' ? 'text' : 'password'} value={values[key]} onChange={e => setValues(v => ({ ...v, [key]: e.target.value }))} placeholder={configured ? 'Leave blank to keep current value' : `Enter ${label.toLowerCase()}`} /><Button type="button" variant="ghost" size="icon" className="absolute right-1 top-1" title={visible[key] ? 'Hide value' : 'Show value'} aria-label={visible[key] ? 'Hide value' : 'Show value'} onClick={() => setVisible(v => ({ ...v, [key]: !v[key] }))}>{visible[key] ? <EyeOff /> : <Eye />}</Button></div><p className="mt-2 text-xs text-muted-foreground">{hint}</p></div>;
  return <div className="max-w-4xl space-y-7"><PageHeading eyebrow="Settings / Security" title="Credentials" description="VPN account details used by your access-point stacks." /><OfflineNotice /><div className="flex items-center gap-3 border-b border-border pb-5 text-sm text-muted-foreground"><LockKeyhole className="size-5 text-primary" /><span>Saved values are never sent back by the Rust service. Blank fields keep their current values.</span></div><form onSubmit={save} className="space-y-8"><section className="space-y-5"><div className="flex items-center gap-2 font-mono text-sm font-semibold"><KeyRound className="size-4 text-primary" /> NordVPN / WireGuard</div><div className="grid gap-5 md:grid-cols-2">{field('nordvpn_token', 'NordVPN access token', 'Saving a token asks the Rust service to fetch and store your WireGuard key.')}{field('wireguard_private_key', 'WireGuard private key', 'Required for NordLynx connections.', status?.has_wireguard_private_key)}</div></section><section className="space-y-5 border-t border-border pt-7"><h2 className="font-mono text-sm font-semibold">OpenVPN service credentials</h2><div className="grid gap-5 md:grid-cols-2">{field('openvpn_user', 'OpenVPN username', 'Your NordVPN service username.', status?.has_openvpn_user)}{field('openvpn_password', 'OpenVPN password', 'Your NordVPN service password.', status?.has_openvpn_password)}</div></section>{error && <p role="alert" className="text-sm text-warning">{error}</p>}<div className="flex justify-end border-t border-border pt-6"><Button type="submit" disabled={!health || busy}><Save /> {busy ? 'Saving…' : 'Save credentials'}</Button></div></form></div>;
}
